<?php

namespace AppBundle\Repository;

/**
 * EstadoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
