<?php

namespace AppBundle\Repository;

/**
 * UsuarioCamposAfinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCamposAfinRepository extends \Doctrine\ORM\EntityRepository
{
}
